# Generated by Django 5.1.1 on 2024-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(to='content.skill'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='dateAndYear',
            field=models.CharField(max_length=40),
        ),
    ]
